# Generated by Django 3.1.7 on 2021-03-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imag',
            new_name='image',
        ),
    ]
